name: hw1

on:
  push:
    branches:
      - '**hw1**'
  pull_request:
    branches:
      - hw1

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-20.04]

        fail-fast: false

    steps:

    - name: setup
      run: echo "${HOME}/opt/conda/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      run: |
        sudo apt-get -qy install python python3

    - name: grade
      run: |
        username=$( [ -z "${{ github.event.pull_request.user.login }}" ] && echo $GITHUB_REPOSITORY | cut -d '/' -f 1 || echo ${{ github.event.pull_request.user.login }})
        echo "cd hw1/$username"
        cd hw1/$username
        ../validate.sh
