name: hw2

on:
  push:
    branches:
      - '**hw2**'
  pull_request:
    branches:
      - hw2

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-20.04]

        fail-fast: false

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make cmake libc6-dev \
            gcc g++ gfortran intel-mkl-full \
            python3 python3-pip python3-pytest \
            python3-numpy python3-scipy python3-pandas python3-matplotlib \
            jupyter
        cd /usr/bin ; sudo ln -sf py.test-3 py.test

    - name: dependency (custom)
      run: |
        export INSTALL_PREFIX=/usr
        sudo contrib/install.sh everything

    - name: grade
      run: |
        username=$( [ -z "${{ github.event.pull_request.user.login }}" ] && echo $GITHUB_REPOSITORY | cut -d '/' -f 1 || echo ${{ github.event.pull_request.user.login }})
        echo "cd hw2/$username"
        cd hw2/$username
        ../validate.sh
